### ISSUE TITLE
getting traceback error

### ISSUE THREAD

**Issue by somedude305** [drivelous/sc-likes#3]
trying to run this tool, i get this (the X's are just my user id and username blurred out, they read fine)

note that im not very experienced with python just trying to download all my liked songs

> Getting user ID for prodthief...
User ID is 431406954
Loading urls of all previously downloaded songs...
Loaded 0 urls
Retrieving all of prodthief's SoundCloud likes...
Traceback (most recent call last):
  File "C:\Python37-32\Scripts\main.py", line 104, in <module>
    main(sys.argv[1])
  File "C:\Python37-32\Scripts\main.py", line 52, in main
    payload = json.loads(requests.get(url + REPEATABLE_PARAMS).content.decode('utf-8'))
  File "C:\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by codiflow** [comment]
Got it working - but I got a Soundcloud GO subscription. As with this its allowed to hear music offline with the Soundcloud App I possibly don't get blocked while downloading my likes. I haven't tested it with a standard account - **maybe you will get blocked. I don't know - so you are doing this at your own risk**

1. Head to the following URL and log into your account: https://soundcloud.com/you/likes
2. In Firefox hit `F12` and go to the "`Network`"-Tab
3. Then on the left click on a song and hit the "`Play`" button, wait about 3 to 4 seconds and hit "`Pause`" (1) then on the right hand side **click** on the entry which starts with `api-v2.soundcloud` in the hosts column and which has "`POST`" in the method column (2)

![grafik](https://user-images.githubusercontent.com/43847817/72208331-bfc59f00-34a1-11ea-979a-e480b25e2a88.png)

4. Now you got the parameters which are needed for the `main.py` file:
- client_id
- app_version
- app_locale

![grafik](https://user-images.githubusercontent.com/43847817/72208456-0ec00400-34a3-11ea-9d68-0df078ec1dcb.png)

5. Just open the `main.py` file with your favorite editor (for me its vim) and change the values to the values you got before. Close and save the file afterwards.

![grafik](https://user-images.githubusercontent.com/43847817/72208530-f69cb480-34a3-11ea-8d37-7189c8493cdf.png)

6. Before you can start downloading you need to change the file `requirements.txt` to grab the most recent youtube-dl version. Otherwise you get lots of "`Error 500 - Internal server error`" messages while downloading.

7. Open the file `requirements.txt` with your favorite editor (for me its vim) and change the value behind `youtube-dl=` to `2020.01.01`. Close and save the file afterwards.

8. Now restart the download of the requirements by entering the following command:
`pip install -r requirements.txt`

9. If everything was successful you can now start to download your likes by entering
`python main.py YOURUSERNAMEHERE`

Hopefully this helps someone.

**Comment by jimfarms13** [comment]
Hey. thanks for figuring all this out. It all worked for me up until I ran the final code "python main.py MYUSERNAME". I was able to run it, but i got a URL open error for every single track it tried to download from my likes, thus none of my likes were downloaded. here is a screenshot of the error: 
<img width="486" alt="Screen Shot 2021-02-26 at 2 03 42 PM" src="https://user-images.githubusercontent.com/76415548/109355299-4111f980-783c-11eb-9f53-bec13128199c.png">
covered the local issuer certificate just in case that was sensitive info i shouldn't give out (i have no idea just being safe)

any ideas on what may be causing this / how to fix it? I'm on MacOS btw

**Comment by jimfarms13** [comment]
Hey, thanks for figuring all of this out. Everything worked for me until the last line of code. I was able to run it, but it gave me a URL open error for every single track it tried to download, thus none of my likes were downloaded. here is a screenshot of the error: 
<img width="486" alt="Screen Shot 2021-02-26 at 2 03 42 PM" src="https://user-images.githubusercontent.com/76415548/109355815-0a88ae80-783d-11eb-9917-2aab5360093d.png">
(covered my name and local issuer certificate. not sure if the certificate is sensitive private info or not, just being safe)

any ideas as to what might be causing this and how I might go about fixing it? I'm on macOS btw.
